### ISSUE TITLE
Saltar Capcha

### ISSUE THREAD

**Issue by ksejan** [jabellcu/DGT_cita_previa#2]
Hola, buenas hay alguna manera de saltarse el captcha, es que necesito cita previa en la DGT urgentemente pero nunca encuentro cita.
Gracias

**Comment by jabellcu** [comment]
Hola, me temo que no. El CAPTCHA está precisamente diseñado para impedir este tipo de herramientas. Requeriría un esfuerzo inmenso saltárselo. De hecho veo que hay compañías comerciales que se dedican a ello (https://brightdata.com/products/web-unlocker/captcha-solver), pero no voy a pagar dinero para usar sus servicios en mi pequeño programa.

**Comment by ksejan** [comment]
Vale gracias por la info.

**Comment by Salahbouaidi** [comment]
Hola cita en murcia cartagena
Canjes marreucos

**Comment by jabellcu** [comment]
> Hola cita en murcia cartagena
> Canjes marreucos

Atención: esto no es un servicio de la DGT. No se ha reservado ninguna cita.

**Comment by henry19874** [comment]
Hi please I've been trying months ago but no appointments can you help?

**Comment by jabellcu** [comment]
Hi! I am very sorry but this no longer works. It’s because they are using captchas precisely to avoid tools like this. If it is any help, it might be easier to get an appointment in a neighbouring region. Good luck.

**Comment by jabellcu** [comment]
Closed as explained in previous comments.

**Comment by henry19874** [comment]
Thanks! I asked because I meet some people use a Robot to take appointments I do not know from where they brought it ... Last week I've been trying all day for Alicante but I couldn't while they could .. but many refuse to share the Robot they use

**Comment by Salahbouaidi** [comment]
Sí, usamos un robot y también lo estoy buscando.

**Comment by henry19874** [comment]
> Sí, usamos un robot y también lo estoy buscando.

Can I have your Whatsapp number please so we look for it together?

**Comment by Salahbouaidi** [comment]
631829426

**Comment by henry19874** [comment]
> 631829426

+0034??

**Comment by Salahbouaidi** [comment]
Si 0034631829426

**Comment by henry19874** [comment]
> Si 0034631829426

ok I texted you there

**Comment by bough12** [comment]
Hola, ¿por qué no funciona la votación en mi PC? Pago por la clave captcha.
